import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import ToasterProvider from "@/components/ui/providers/toaster-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("pk_test_Y29taWMtc3dpbmUtMzcuY2xlcmsuYWNjb3VudHMuZGV2JA")
  return (
    <ClerkProvider
      // publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      publishableKey={"pk_test_Y29taWMtc3dpbmUtMzcuY2xlcmsuYWNjb3VudHMuZGV2JA"}
    >
      <html lang="en">
        <body className={inter.className}>
          <ToasterProvider/>
          {children}
          </body>
      </html>
    </ClerkProvider>
  );
}
